name: Python CI with Slack Notification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set job status
      id: set_status
      run: echo "status=${{ job.status }}" >> $GITHUB_ENV
      
    - name: Post to a Slack channel (Success)
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
        payload: |
          {
            "text": "GITHUB Action result: *${{ env.JOB_STATUS_UPPERCASE }}*",
            "attachments": [
              {
                "color": "#0aff43",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Self-study Hiragana & Katakana push result: ${{ env.JOB_STATUS_UPPERCASE }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        JOB_STATUS_UPPERCASE: '✅ Success'

    - name: Post to a Slack channel (Cancelled)
      if: ${{ cancelled() }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
        payload: |
          {
            "text": "GITHUB Action result: *${{ env.JOB_STATUS_UPPERCASE }}*",
            "attachments": [
              {
                "color": "#ffd51c",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Self-study Hiragana & Katakana push result: ${{ env.JOB_STATUS_UPPERCASE }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        JOB_STATUS_UPPERCASE: '🚫 Cancelled'

    - name: Post to a Slack channel (Other)
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
        payload: |
          {
            "text": "GITHUB Action result: *${{ env.JOB_STATUS_UPPERCASE }}*",
            "attachments": [
              {
                "color": "#ff19b3",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Self-study Hiragana & Katakana push result: ${{ env.JOB_STATUS_UPPERCASE }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        JOB_STATUS_UPPERCASE: '❌ Failed'
